### PR TITLE
Add Image Tool Functionality

### PR DESCRIPTION
**Pull request by wgranger**
This pr adds functionality for all image tools you can view by hovering over a subject. You can test these in storybook. I also added a refresh button and tests.

### CODE REVIEW

**Comment by shaunanoordin** [comment]
I'm not sure if this branch is functioning, as any attempt to run `yarn storybook` results in an error.

- After deleting `node_modules` and re-running `yarn install`...
- ...running `yarn storybook` results in errors like" `ERROR in ./src/components/SubjectViewer/SubjectViewerContainer.js
Module not found: Error: Can't resolve 'store' in '/Users/shaun/projects/text-editor/src/components/SubjectViewer'` in both the bash console and in `http://localhost:6006/`
- Note: I can still view the normal web app, e.g. `yarn start` -> `http://localhost:3000/projects/workflows/subject-sets/subjects/edit`, just fine.

**Comment by wgranger** [comment]
Ahh right. Storybook is crashing on the absolute imports I have for the store. Let me see if I can find a workaround. I failed to notice this crashed storybook when completing this branch.

**Comment by eatyourgreens** [comment]
If you’re using webpack aliases, you’ll have to pass them to the storybook. https://github.com/zooniverse/front-end-monorepo/pull/1165

**Comment by shaunanoordin** [comment]
I'm not familiar enough with Storybook to suggest a specific solution. However, if it's based on `webpack`, the latest versions allow for `alias` paths using [`modules.exports.resolve.alias = {...}`](https://webpack.js.org/configuration/resolve/)

So you can do something like...

```
// in webpack...
module.exports = {
  resolve: {
    alias: {
      'MyStoreDirectory': path.resolve(__dirname, 'src/stores/'),
     }
  }
}

// in your component...
import store from `MyStoreDirectory`
```

**Comment by shaunanoordin** [comment]
What Jim said! 😄☝️

**Comment by eatyourgreens** [comment]
If you’re testing with mocha, you might also need the mocha config changes from that PR.

**Comment by wgranger** [comment]
Thanks for the comments! I had to use a slightly different approach since I'm limited to webpack configuration with create-react-app. I put the following into `webpack.config.js` in the `.storybook` folder.

```
const path = require('path')

module.exports = (baseConfig, env, config) => {
  config.resolve.modules = [
    ...(config.resolve.modules || []),
    path.resolve(__dirname, "../src")
  ];

  return config;
}
```

**Comment by wgranger** [comment]
Also, several of these tests will fail until I can get these changes into the panoptes-client. You'll have to monkey patch for now.

https://github.com/zooniverse/panoptes-javascript-client/pull/119

**Pull request merged**
