### PR TITLE
Add SearchModal

### PR DESCRIPTION
**Pull request by wgranger**
This PR adds the SearchModal components while also allowing the form to function using Formik and Mobx

### CODE REVIEW

**Comment by wgranger** [comment]
As always, thanks for the thorough review. I'll address these ❓questions before merge so I don't have to come back to this in the future. I'll try to get this taken care of today.

**Comment by wgranger** [comment]
Form validation should now be working properly, but please let me know if there is anything left outstanding.

**Comment by beckyrother** [comment]
Completely agree, and I like the error message but I'd modify it to "Select an ID type" to be a bit more specific and help people find what they're supposed to select

**Comment by wgranger** [comment]
👍 Just updated validations based on our discussion.

**Comment by shaunanoordin** [comment]
New validation updates work great. 👍 LGTM!

**Pull request merged**
