### PR TITLE
Add About Content

### LINKED ISSUE #148: Add help text to about page
Add the linked text to alice.zooniverse.org/about: [Google Doc](https://docs.google.com/document/d/1l47T0gScsUC6CiavmcWfPUdryFzF6nWYc2V0FsDdIfI/edit?usp=sharing)

Note: I will open a separate issue with a link to image files. Please use image file names as placeholders for the time being.

### LINKED ISSUE #151: Help page design feedback
- [x] max width for the text block should be 800px (any wider and it gets hard to read) (does not apply to images, which can stay the same sizing as they currently are)
- [x] left-align images (ty Nicole)
- [x] add 1em spacing between paragraphs
- [x] max-width on H4 seems to be less than everywhere else? 
- [x] increase body font size to 16px

Contents:
Text weights for levels is good but
- [ ] Don't capitalize the secondary links
- [x] Add 1em between major sections (ie above 'Using ALICE with your team')

Elsewhere:
- [x] dropdown on profile is very tiny, add padding to top and bottom so each option has 44px height (#156)
current:
image
invision: 
image

### PR DESCRIPTION
**Pull request by wgranger**
This PR adds content to the about page to reflect the [Invision Design](https://projects.invisionapp.com/d/main#/console/17925240/394207098/preview). This branch is also currently staged at [alice.preview.zooniverse.org/about](https://alice.preview.zooniverse.org/about). A couple items to note:

- I initially attempted to use markdown entirely to feed in content from a JS object into a reusable `AboutContent` component, but I abandoned this for accessibility reasons and to keep the code from getting too rigid. That said, this PR covers a bit more lines and earlier commits here aren't reflective of the final result.
- The `ContentTable` component has some `setState` code to determine the height of the table of contents. This was necessary as the component's `position: sticky` div needed a defined height to allow it to work properly.

Closes #148 
Closes #151 

tagging @beckyrother to provide UI feedback using the link above

### CODE REVIEW

**Comment by wgranger** [comment]
Converting this to a draft as we make a few design and content changes.

**Comment by shaunanoordin** [comment]
## Quick Review

- Content update looks legit to me.
- I should give it an Accessibility pass for good measure.
- [minor] A curious note, when I'm not logged in:
  - I can navigate to the About page from the home page ("Link to Documentation" link) just fine.
  - However, when I type in http://localhost:3000/about directly in the web browser's URL bar, I get shunted back to the home page.

As far as I'm concerned, this PR already has a 👍 for the functionality side of things.

**Comment by snblickhan** [comment]
@wgranger Here are the requested updates to About page. Ping me if anything below is unclear.

THROUGHOUT THE DOC:
- [ ] Can we add a space break between paragraphs? I’m finding it quite difficult to read in the current format. For example, in the **Getting started** section, the first paragraph ends with the words "read on." the next paragraph starts with "To build your transcription project, ... " There's a line break, but no space between the paragraphs. For ease of reading, I'd like to add a single space between paragraphs in the same section, but would defer to @beckyrother re: convention.

- [ ] Need to make a choice regarding using bold or ‘single quotes’ to reflect buttons/options. @beckyrother do you have a preference for this one? Or just consistency? Note: I'll add specific requests for changes once I've had a chance to communicate with Becky about this.

SPECIFIC COMMENTS (section header in **bold** for ease of finding):
**Reaching out to complete your setup**
- [ ]  space missing between ‘To do _so,please_ email contact@zooniverse.org’

**Adding team members & levels of access**
- [ ] Missing explanatory text for ‘Viewer access: Tester’.  Should read as follows (following the same format as previous User options):

Viewers are able to do the following:
- View subjects


**Viewing subjects**
- [ ] “For each subject[_change subject here to group_], you will be able to see (and sort by!) the following information:”

**Search**

- [ ] Add this sentence at the end of the paragraph (after sentence ending with “…by clicking on the available column headings.”): “Please note that ALICE only supports search within individual groups, not across an entire Workflow or Project.”

**What am I looking at? Images, markings, and transcriptions**
- [ ] Please update final sentence: “For each individual transcription, you will see the Zooniverse username of the volunteer who submitted it (if they are[_change to were_] logged into a Zooniverse account), and the time and date the transcription was submitted.”

**OPTICS**
- [ ] “Adjustable Parameters” needs to be a sub-heading of OPTICS

**DBSCAN**
- [ ] “Adjustable parameters” needs to be in bold and should be a sub-heading of DBSCAN

**Comment by beckyrother** [comment]
Thanks @snblickhan! The first comment looks like it's been covered based on the checked item in #151 ('add 1em space between paragraphs`)

Bold vs single quotes, I'd suggest single quotes in case someone is viewing in plain text for some reason. But really, consistency is the most important thing.

**Comment by snblickhan** [comment]
Standardize formatting for referring to buttons (see above re: **bold** vs 'single quotes'):

Getting Started:
- [ ] "Create your account by visiting https://www.zooniverse.org and clicking REGISTER[change from bold to 'REGISTER']."
- [ ] "To create a project, visithttps://www.zooniverse.org/lab, sign into your account, and click Create a new project[change from bold to 'Create a new project']."

Setting up your project for use with ALICE:
- [ ] Please set up your workflow using the Line Tool with a Text Entry Sub-task[remove bold].
- [ ] "Select Add A Task[change from bold to 'Add A Task'] > Drawing[change from bold to 'Drawing']."
- [ ] "In the Tool Selection Area[remove bold], choose Line[change from bold to 'Line'] and add a Text Sub-task[change from bold to 'Text Sub-task']."
- [ ] image caption 'SERIES ILLUSTRATING THE PROCESS OF CREATING...': remove all bold from this caption.

Uploading subjects
- [ ] "To add metadata to your subjects, include a manifest[remove bold] in your subject upload."
- [ ] "The metadata can be accessed by volunteers within Project Builder projects (in the transcription interface), as well as by your collaborators in ALICE (on individual Subject[remove bold] pages)."
- [ ] change Internal_ID to internal_id in first bullet point [leave as bold]
- [ ] change Group_ID to group_id in second bullet point [leave as bold]
- [ ] "The Group_ID[change to group_id] can be the Subject Set Name or ID used in the Project Builder, or you can choose another name. The Group ID[change to group_id] will be the sub-index for a given workflow

Using ALICE with your team:
Search
- [ ] "Clicking the Search[change from bold to 'Search'] button will open a pop-up module..."
- [ ] "To search for a specific subject, select the ID type (Zooniverse ID or Internal ID), enter the name, and click Search[change from bold to 'Search']."

Editing
- [ ] "To change it, select an individual transcription from the list, or write your own in the space provided, and click Replace with selected[change from bold to 'Replace with selected']."
- [ ] "To revert to the aggregated transcription, click on the line to reopen the module, select the aggregated transcription from the menu, and click Replace with selected.[change from bold to 'Replace with selected']."

Approving subjects 
- [ ] "To un-approve a subject, click the Approve button at the top of the page[add single quotes to 'Approve']"

NOTE: Unless noted above, all other currenlty-bold words can remain bold.

Other updates/typo fixes for About page:
- [ ] "What am I looking at? Images, markings, and transcriptions" has a line break between "and" & "transcriptions" that needs to be removed.

**Comment by snblickhan** [comment]
- [ ] Add text to "What am I looking at?" section (following the sentence "Each solid line represents a cluster of individual lines drawn by volunteers, which are represented by dotted lines of the same color."): Circles at the end of each line represent the dots placed by volunteers to generate the underline marking. An open circle represents the first dot placed by a volunteer; a closed circle represents the second dot.

**Pull request merged**
